# Generated by Django 6.0.1 on 2026-07-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProId', models.IntegerField()),
                ('ProName', models.CharField(max_length=40)),
                ('ProImg', models.CharField(max_length=100)),
                ('ProPrice', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
