# Generated by Django 6.0.1 on 2026-08-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
