# Generated by Django 6.0.1 on 2026-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.IntegerField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=50)),
                ('StudentMarks', models.IntegerField()),
            ],
        ),
    ]
