# Generated by Django 6.0.1 on 2026-07-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StuId', models.IntegerField(primary_key=True, serialize=False)),
                ('StuName', models.CharField(max_length=40)),
                ('StuMarks', models.IntegerField()),
                ('StuImg', models.CharField(max_length=200)),
            ],
        ),
    ]
