# Generated by Django 6.0.1 on 2026-07-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.IntegerField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=40)),
                ('EmployeeSalary', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
