# Generated by Django 6.0.1 on 2026-08-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employoee',
            fields=[
                ('EmpId', models.IntegerField(primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=50)),
                ('EmpSal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
